/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavBar: typeof import('./components/AppNavBar.vue')['default']
    CountDownPopup: typeof import('./components/CountDownPopup.vue')['default']
    DeviceDrawer: typeof import('./components/DeviceDrawer.vue')['default']
    DeviceLogPanel: typeof import('./components/DeviceLogPanel.vue')['default']
    M1DataCard: typeof import('./components/M1DataCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensorValue: typeof import('./components/SensorValue.vue')['default']
    TaskEditPopup: typeof import('./components/TaskEditPopup.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    Zm1SettingOtaProgress: typeof import('./components/Zm1SettingOtaProgress.vue')['default']
    Zm1SettingTextDialog: typeof import('./components/Zm1SettingTextDialog.vue')['default']
    Zm1SettingZonePicker: typeof import('./components/Zm1SettingZonePicker.vue')['default']
  }
}
